RedstoneGroup = (('redstone', ({'outputQty': 9, '红石块': 1},), '红石粉', '红石方块'),
                 ('redstone_torch', ({'outputQty': 1, '红石粉': 1, '木棍': 1},), '红石火把', '红石方块'),
                 ('redstone_block', ({'outputQty': 1, '红石粉': 9},), '红石块', '红石方块'),
                 ('repeater', ({'outputQty': 1, '红石粉': 1, '红石火把': 2, '石头': 3},), '红石中继器', '红石方块'),
                 ('comparator', ({'outputQty': 1, '石英': 1, '红石火把': 3, '石头': 3},), '红石比较器', '红石方块'),
                 ('target', ({'outputQty': 1, '红石粉': 4, '干草块': 1},), '标靶', '红石方块'),
                 ('lever', ({'outputQty': 1, '圆石': 1, '木棍': 1},), '拉杆', '红石方块'),
                 ('wood_pressure_plate', ({'outputQty': 1, '木板': 2},), '木制压力板', '红石方块'),
                 ('stone_pressure_plate', ({'outputQty': 1, '石头': 2},), '石制压力板', '红石方块'),
                 ('light_weighted_pressure_plate', ({'outputQty': 1, '金锭': 2},), '轻质测重压力板', '红石方块'),
                 ('heavy_weighted_pressure_plate', ({'outputQty': 1, '铁锭': 2},), '重质测重压力板', '红石方块'),
                 ('calibrated_sculk_sensor', ({'outputQty': 1, '紫水晶碎片': 3, '幽匿感测体': 1},), '校频幽匿感测体', '红石方块'),
                 ('tripwire_hook', ({'outputQty': 2, '铁锭': 1, '木棍': 1, '木板': 1},), '拌线钩', '红石方块'),
                 ('lectern', ({'outputQty': 1, '木制台阶': 4, '书架': 1},), '讲台', '红石方块'),
                 ('daylight_detector', ({'outputQty': 1, '玻璃': 3, '石英': 3, '木制台阶': 3},), '阳光探测器', '红石方块'),
                 ('lightning_rod', ({'outputQty': 1, '铜锭': 3},), '避雷针', '红石方块'),
                 ('piston', ({'outputQty': 1, '红石粉': 1, '木板': 3, '铁锭': 1, '圆石': 4},), '活塞', '红石方块'),
                 ('sticky_piston', ({'outputQty': 1, '黏液球': 1, '活塞': 1},), '黏性活塞', '红石方块'),
                 ('slime_block', ({'outputQty': 1, '黏液球': 9},), '黏液块', '红石方块'),
                 ('honey_block', ({'outputQty': 1, '蜂蜜瓶': 4},), '蜂蜜块', '红石方块'),
                 ('dispenser', ({'outputQty': 1, '红石粉': 1, '弓': 1, '圆石': 7},), '发射器', '红石方块'),
                 ('dropper', ({'outputQty': 1, '红石粉': 1, '圆石': 7},), '投掷器', '红石方块'),
                 ('hopper', ({'outputQty': 1, '铁锭': 5, '箱子': 1},), '漏斗', '红石方块'),
                 ('chest', ({'outputQty': 1, '木板': 8},), '箱子', '红石方块'),
                 ('barrel', ({'outputQty': 1, '木板': 6, '木制台阶': 2},), '木桶', '红石方块'),
                 ('chiseled_bookshelf', ({'outputQty': 1, '木板': 6, '木制台阶': 3},), '雕纹书架', '红石方块'),
                 ('furnace', ({'outputQty': 1, '圆石': 8},), '熔炉', '红石方块'),
                 ('trapper_chest', ({'outputQty': 1, '箱子': 1, '绊线钩': 1},), '陷阱箱', '红石方块'),
                 ('observer', ({'outputQty': 1, '石英': 1, '红石粉': 2, '圆石': 6},), '侦测器', '红石方块'),
                 ('note_block', ({'outputQty': 1, '红石粉': 1, '木板': 8},), '音符盒', '红石方块'),
                 ('composter', ({'outputQty': 1, '木制台阶': 7},), '堆肥桶', '红石方块'),
                 ('cauldron', ({'outputQty': 1, '铁锭': 7},), '炼药锅', '红石方块'),
                 ('rail', ({'outputQty': 16, '木棍': 1, '铁锭': 6},), '铁轨', '红石方块'),
                 ('powered_rail', ({'outputQty': 6, '红石粉': 1, '木棍': 1, '金锭': 6},), '动力铁轨', '红石方块'),
                 ('detector_rail', ({'outputQty': 6, '红石粉': 1, '石头压力板': 1, '铁锭': 6},), '探测铁轨', '红石方块'),
                 ('activator_rail', ({'outputQty': 6, '红石火把': 1, '木棍': 2, '铁锭': 6},), '激活铁轨', '红石方块'),
                 ('minecart', ({'outputQty': 1, '铁锭': 5},), '矿车', '红石方块'),
                 ('hopper_minecart', ({'outputQty': 1, '漏斗': 1, '矿车': 1},), '漏斗矿车', '红石方块'),
                 ('chest_minecart', ({'outputQty': 1, '箱子': 1, '矿车': 1},), '运输矿车', '红石方块'),
                 ('furnace_minecart', ({'outputQty': 1, '熔炉': 1, '矿车': 1},), '动力矿车', '红石方块'),
                 ('tnt_minecart', ({'outputQty': 1, 'TNT': 1, '矿车': 1},), 'TNT矿车', '红石方块'),
                 ('chest_boat', ({'outputQty': 1, '箱子': 1, '木船': 1},), '木运输船', '红石方块'),
                 ('chest_raft', ({'outputQty': 1, '箱子': 1, '竹筏': 1},), '运输竹筏', '红石方块'),
                 ('door', ({'outputQty': 3, '木板': 6},), '门', '红石方块'),
                 ('iron_door', ({'outputQty': 3, '铁锭': 6},), '铁门', '红石方块'),
                 ('fence_gate', ({'outputQty': 1, '木棍': 4, '木板': 2},), '栅栏门', '红石方块'),
                 ('trapdoor', ({'outputQty': 2, '木板': 6},), '活板门', '红石方块'),
                 ('iron_trapdoor', ({'outputQty': 1, '铁锭': 4},), '铁活板门', '红石方块'),
                 ('tnt', ({'outputQty': 1, '火药': 5, '沙子': 4},), 'TNT', '红石方块'),
                 ('redstone_lamp', ({'outputQty': 1, '红石粉': 4, '荧石': 1},), '红石灯', '红石方块'),
                 ('armor_stand', ({'outputQty': 1, '木棍': 6, '平滑石台阶': 1},), '盔甲架', '红石方块'),
                 ('netherite_ingot', ({'outputQty': 1, '金锭': 4, '下界合金碎片': 4},
                                      {'outputQty': 9, '下届合金块': 1},), '下界合金锭', '红石方块'),)
